#!/usr/bin/env bash
# Install haproxy and config 2 server
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 50442-web-01 35.153.98.66 check\n\tserver 50442-web-02 35.153.51.98 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
